# Generated by Django 3.2.8 on 2021-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
